spring:
  application:
    name: Cjpa
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/xe
    username: hr
    password: hr
  jpa: #??? ?? ???? ??, ??? ???? ?? ???? ?.
    open-in-view: false #jpa ?? ? ? ?? ?.
    generate-ddl: true #ddl ?? ??? ?
    show-sql: true #sql ? ? ??
    hibernate:
      ddl-auto: update #??? ??. create: ?? table ?? ? ?? ??. update: ?? ???? ??? ??
    properties:
      hibernate:
        show_sql: true #????
        format_sql: true


server:
  port: 5432